apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gitops
spec:
  replicas: 3 # Empezaremos con 1 réplica
  selector:
    matchLabels:
      app: demo-gitops
  template:
    metadata:
      labels:
        app: demo-gitops
    spec:
      containers:
        - name: web
          image: viclexis/app-unmsm:latest # Tu imagen de Docker Hub
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-gitops
spec:
  type: NodePort
  selector:
    app: demo-gitops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Puerto fijo para fácil acceso

