name: CI Pipeline - Build & Push

# Trigger: Se ejecuta en cada 'push' a la rama "main"
on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest # El servidor de GitHub que ejecutará el trabajo
    
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3
        
      # 2. Loguearse en Docker Hub (Usando los secretos)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # 3. Construir la imagen y subirla (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Etiquetamos como 'latest' y también con el Hash del commit (para trazabilidad)

          tags: |
            ${{ secrets.DOCKER_USERNAME }}/app-unmsm:latest
          ${{ secrets.DOCKER_USERNAME }}/app-unmsm:${{ github.sha }}
